# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Cálculo Multivariables 2025-1
author: The Jupyter Book Community/ Área de Matemáticas FIC UAI/ Denis Osses, denis.osses@uai.cl
copyright: "2025-1"
logo: logomat.jpeg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  use_jupyterbook_latex: true
  latex_engine: pdflatex
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/DenisOsses/CursoMulti  # Online location of your book
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  #branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository

html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: true
  # google_analytics_id: G-TW65QWSB9F
  # analytics:
  #   google_analytics_id: G-TW65QWSB9F

# Enable parsing LaTeX-style math blocks with the amsmath MyST extension
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
    - colon_fence
    - html_admonition
  myst_dmath_double_inline: true
  
launch_buttons:
  #binderhub_url: "https://mybinder.org/v2/gh/DenisOsses/CursoEdo/HEAD"
  thebe: true
  colab_url: "https://colab.research.google.com"
  
extensions:
    myst_parser: true
    sphinx_design: true
    
sphinx:
  config:
    language: es
    templates_path:
      - _templates
 
